### ISSUE TITLE
Uses Clojure 1.4

### ISSUE THREAD

**Issue by GHExplorer** [ifesdjeen/enlive-ring#1]
The project uses Clojure 1.4, and older versions of Ring and Enlive.

Will there be any updates, with some buttons redefined in the clojure source?  That would be a more complete sample.

As of 08/30/2015, this would be an updated project.clj:

(defproject com.ifesdjeen.enlive-ring "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :dependencies [[ring "1.4.0"]
                 [compojure "1.1.3" :exclude [clout]]
                 [clout "2.1.2"]
                 [enlive "1.1.6"]
                 [org.clojure/clojure "1.7.0"]]
  :plugins [[lein-ring "0.9.6"]]
  :ring {:handler com.ifesdjeen.enlive-ring.core/app})

**Comment by ifesdjeen** [comment]
This is just an example application. Which Clojure version you use is rather orthogonal to what's possible to do with Enlive.
